import { TChildren } from "@/types";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next.js Full Course",
  description: "Generated by Salman Ahamed",
};

const RootLayout = ({ children }: TChildren) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-10 min-h-screen `}
      >
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
