#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged
bunx lint-staged

# Additional checks
echo "Running additional style checks..."
bunx stylelint "**/*.{css,scss}" --max-warnings 0
bunx eslint . --max-warnings 0
